server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/homefood/config-repo}
          default-label: main
          timeout: 10
          clone-on-start: false
  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka:eureka123@localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,refresh,bus-refresh
  endpoint:
    health:
      show-details: always
